version: '3'
services:
  assembly-db:
    image: postgres
    container_name: assembly-db
    restart: always
    environment:
      - POSTGRES_DB=assembly-db
      - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:3.7.8-management'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - 'WAIT_HOSTS=assembly-db:5432'
    depends_on:
      - assembly-db
    
  keycloak:
    image: jboss/keycloak:4.8.3.Final
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: assembly-db
        DB_USER: adm
        DB_SCHEMA: public
        DB_PASSWORD: 123
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - '8085:8080'
    depends_on:
      - assembly-db
    
  user-api:
    build: ./user-api
    container_name: user-api
    ports:
      - '8081:8080'
    environment:
      WAIT_HOSTS: 'assembly-db:5432, rabbitmq:5672'
    depends_on:
      - assembly-db
      - rabbitmq

  session-api:
    build: ./session-api
    container_name: session-api
    ports:
      - '8082:8080'
    environment:
      WAIT_HOSTS: 'assembly-db:5432, rabbitmq:5672, user-api:8081'
    depends_on:
      - assembly-db
      - user-api
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - '8080:8084'
    environment:
      WAIT_HOSTS: 'assembly-db:5432, rabbitmq:5672, user-api:8081, session-api:8082'
    depends_on:
      - user-api
      - session-api

