version: '3'
services:
  assembly-db:
    image: postgres
    container_name: assembly-db
    restart: always
    environment:
      - POSTGRES_DB=assembly-db
      - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'

  rabbitmq:
    image: 'rabbitmq:3.7.8-management'
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - 'WAIT_HOSTS=assembly-db:5432'
    depends_on:
      - assembly-db
    

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.1
    container_name: keycloak
    restart: always
    ports:
      - '8081:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    depends_on:
      - assembly-db
      - rabbitmq
    volumes:
      - ./keycloak/data/
    
  user-api:
    build: ./user-api
    container_name: user-api
    ports:
      - '8082:8080'
    environment:
      WAIT_HOSTS: 'assembly-db:5432, rabbitmq:5672'
    depends_on:
      - assembly-db
      - rabbitmq

  session-api:
    build: ./session-api
    container_name: session-api
    ports:
      - '8083:8080'
    environment:
      WAIT_HOSTS: 'assembly-db:5432, rabbitmq:5672, user-api:8081'
    depends_on:
      - assembly-db
      - rabbitmq
      - user-api

#  gateway:
#    build: ./gateway
#    container_name: gateway
#    ports:
#      - '9090:9090'
#    environment:
#      WAIT_HOSTS: 'assembly-db:5432, rabbitmq:5672, user-api:8081, session-api:8082'
#    depends_on:
#      - user-api
#      - session-api
#      - keycloak

