version: '3'
services:
  assembly-db:
    image: postgres
    container_name: assembly-db
    restart: always
    environment:
      - POSTGRES_DB=assembly-db
      - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:3.7.8-management'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - 'WAIT_HOSTS=assembly-db:5432'
    depends_on:
      - assembly-db
  user-api:
    build: ./user-api
    container_name: user-api
    ports:
      - '8081:8080'
    environment:
      WAIT_HOSTS: 'assembly-db:5432, rabbitmq:5672'
    depends_on:
      - assembly-db
      - rabbitmq
  session-api:
    build: ./session-api
    container_name: session-api
    ports:
      - '8082:8080'
    environment:
      WAIT_HOSTS: 'assembly-db:5432, rabbitmq:5672, user-api:8081'
    depends_on:
      - assembly-db
      - user-api
  getway:
    build: ./getway
    container_name: getway
    ports:
      - '8080:8080'
    environment:
      WAIT_HOSTS: 'assembly-db:5432, rabbitmq:5672, user-api:8081, session-api:8082'
    depends_on:
      - user-api
      - session-api

