version: '3.1'

services:

   assembly-db:
      image: postgres
      container_name: assembly-db
      restart: always
      environment:
         - POSTGRES_DB=assembly-db
         - POSTGRES_USER=adm
         - POSTGRES_PASSWORD=123
      ports:    
         - 5432:5432

  
   rabbitmq:
      image: rabbitmq:3.7.8-management
      container_name: rabbitmq
      ports:
         - 5672:5672
         - 15672:15672
      environment:
         - RABBITMQ_DEFAULT_USER=rabbitmq
         - RABBITMQ_DEFAULT_PASS=rabbitmq
         
   session-api:
        build: './session-api'
        container_name: session-api
        ports:
           - 8081:8080
        depends_on:
            - assembly-db

  
