server:
    port: 8081

spring:
    
   application:
       name: session-api
       
   datasource:
       driver-class-name: org.postgresql.Driver
       url: jdbc:postgresql://localhost:5432/assembly-db
       username: adm
       password: 123
       initialization-mode: always
       initialize: true
       continue-on-error: true
       platform: postgresql

  # JPA properties
   jpa:
       hibernate:
       ddl-auto: update 
       show-sql: true
       database: postgresql
       database-platform: org.hibernate.dialect.PostgreSQLDialect
       open-in-view: false
       generate-ddl: true   
   
   rabbitmq:
      host: localhost
      port: 5672
      username: rabbitmq
      password: rabbitmq
