server:
   port: 8082

spring:
    
   application:
       name: session-api
       
   datasource:
       driver-class-name: org.postgresql.Driver
       url: jdbc:postgresql://172.22.0.2:5432/assembly-db
       username: adm
       password: 123
       initialization-mode: always
       initialize: true
       continue-on-error: true
       platform: postgresql

  # JPA properties
   jpa:
       hibernate:
          ddl-auto: update 
          format_sql: true
       show-sql: true
       properties:
          hibernate:
             dialect: org.hibernate.dialect.PostgreSQL9Dialect
       open-in-view: false
       generate-ddl: true   
   
   rabbitmq:
      host: 172.22.0.3
      port: 5672
      username: rabbitmq
      password: rabbitmq
      
   security:
      oauth2:
         client:
            provider:
               my-keycloak-provider:
                  issuer-uri: http://localhost:8081/auth/realms/AssemblyVotes
            registration:
               keycloak-assembly-sessions:
                  provider: my-keycloak-provider
                  client-id: assembly-sessions
                  client-secret: 58f07a10-41b7-4a45-8e03-a5b4b7640ebb
                  authorization-grant-type: authorization_code
                  redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'
