server:
   port: 8084

spring:
   application:
      name: auth-api
      
   datasource:
       driver-class-name: org.postgresql.Driver
       url: jdbc:postgresql://172.22.0.2:5432/assembly-db
       username: adm
       password: 123
       initialization-mode: always
       initialize: true
       continue-on-error: true
       platform: postgresql
       
  # JPA properties
   jpa:
       hibernate:
          ddl-auto: update 
          format_sql: true
       show-sql: true
       properties:
          hibernate:
             dialect: org.hibernate.dialect.PostgreSQL9Dialect
       open-in-view: false
       generate-ddl: true   
       
